resolved staticheck errors
errors resolved:
internal\proxy\proxy.go:71:21: argument should be pointer-like to avoid allocations (SA6002)
internal\proxy\proxy_test.go:46:25: func (*recordingSink).waitOne is unused (U1000)
internal\store\store.go:170:25: error strings should not be capitalized (ST1005)